#include "mainwindow.h"
#include "gl_video_widget.h"
#include "serial_worker.h"
#include "ai_receiver.h"
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonArray>
#include <QCloseEvent>
#include <QProcess>
#include <QCoreApplication>
#include <QDir>
#include <QTimer>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QKeyEvent>
#include <QSplitter>
#include <QDateTime>
#include <QDebug>

MainWindow::MainWindow(QWidget* parent)
    : QMainWindow(parent)
{
    initUi();

    QString app_dir = QCoreApplication::applicationDirPath();
    QString runtime_dir = qEnvironmentVariable("WEBRTC_RUNTIME_DIR",
                                               QString("/tmp/webrtc_runtime"));
    QDir().mkpath(runtime_dir);

    log_file_ = new QFile(runtime_dir + "/ui_rk.log", this);
    log_file_->open(QIODevice::Append | QIODevice::Text);

    QString daemon_path = qEnvironmentVariable("WEBRTC_DAEMON_PATH",
        app_dir + "/client_arm64");

    proc_mgr_ = new WebRtcProcessManager(daemon_path, this);
    QProcessEnvironment env = QProcessEnvironment::systemEnvironment();
    env.insert("WEBRTC_RUNTIME_DIR", runtime_dir);
    proc_mgr_->process()->setProcessEnvironment(env);

    channel_ = new ControlChannel(runtime_dir + "/webrtc_ctrl.sock", this);

    initConnections();

    serial_ = new SerialWorker("/dev/ttyS9", 115200, this);
    connect(serial_, &SerialWorker::errorOccurred, this, [this](const QString& e) {
        log("Serial: " + e);
    });
    connect(serial_, &SerialWorker::received, this, [this](const QString& json) {
        log("MCU: " + json);
    });
    serial_->start();

    qRegisterMetaType<QVector<Detection>>("QVector<Detection>");
    ai_receiver_ = new AiReceiver("/tmp/webrtc_runtime/ai_detections.sock", this);
    connect(ai_receiver_, &AiReceiver::detectionsReady, this, &MainWindow::onAiDetections);
    ai_receiver_->start();

    // Voice chat
    voice_mgr_ = new VoiceChatManager(this);
    connect(voice_mgr_, &VoiceChatManager::daemonLog, this, &MainWindow::log);

    QString vc_socket = runtime_dir + "/voice_chat.sock";
    voice_client_ = new VoiceChatClient(vc_socket, this);
    connect(voice_client_, &VoiceChatClient::asrResult, this,
            [this](const QString& t) { chatLog("You: " + t); });
    connect(voice_client_, &VoiceChatClient::llmResult, this,
            [this](const QString& t) { chatLog("Bot: " + t); });
    connect(voice_client_, &VoiceChatClient::errorOccurred, this,
            [this](const QString& e) { log("VoiceChat error: " + e); });
    connect(voice_client_, &VoiceChatClient::connected, this, [this]() {
        log("VoiceChat socket connected, waiting for ready...");
    });
    connect(voice_client_, &VoiceChatClient::ready, this, [this]() {
        log("VoiceChat ready, starting conversation");
        voice_client_->cmdStart();
    });

    connect(action_voice_chat_, &QAction::triggered,
            this, &MainWindow::toggleVoiceChat);

    key_timer_ = new QTimer(this);
    key_timer_->setInterval(80);
    connect(key_timer_, &QTimer::timeout, this, [this]() {
        if (held_key_ == Qt::Key_W)      sendSerialJson("{\"cmd\":\"move\",\"v\":0.5,\"w\":0}");
        else if (held_key_ == Qt::Key_A) sendSerialJson("{\"cmd\":\"move\",\"v\":0,\"w\":0.8}");
        else if (held_key_ == Qt::Key_S) sendSerialJson("{\"cmd\":\"move\",\"v\":-0.3,\"w\":0}");
        else if (held_key_ == Qt::Key_D) sendSerialJson("{\"cmd\":\"move\",\"v\":0,\"w\":-0.8}");
        else if (held_key_ == Qt::Key_Up)    sendSerialJson("{\"cmd\":\"ptz\",\"pan\":0,\"tilt\":0.5}");
        else if (held_key_ == Qt::Key_Down)  sendSerialJson("{\"cmd\":\"ptz\",\"pan\":0,\"tilt\":-0.5}");
        else if (held_key_ == Qt::Key_Left)  sendSerialJson("{\"cmd\":\"ptz\",\"pan\":-0.5,\"tilt\":0}");
        else if (held_key_ == Qt::Key_Right) sendSerialJson("{\"cmd\":\"ptz\",\"pan\":0.5,\"tilt\":0}");
    });

    log("Starting WebRTC daemon...");
    proc_mgr_->start();
}

MainWindow::~MainWindow() = default;

void MainWindow::closeEvent(QCloseEvent* event) {
    channel_->cmdShutdown();
    proc_mgr_->stop();
    stopVideoSources();
    stopAi();
    stopVoiceChat();
    event->accept();
}

void MainWindow::initUi() {
    // Load widget tree from .ui file (generated by uic)
    ui.setupUi(this);

    // Find runtime pointers from .ui layout (copied from x64: QSplitter layout)
    remote_container_ = centralWidget()->findChild<QWidget*>("remote_container_");
    if (remote_container_) {
        remote_container_->setObjectName("remoteContainer");
    }

    // Create local_video_ (PIP overlay) in remote_container_
    local_video_ = new GlVideoWidget(remote_container_);
    local_video_->setObjectName("localVideo");
    local_video_->setMinimumSize(160, 120);
    local_video_->setMaximumSize(480, 360);
    local_video_->setStyleSheet(
        "border: 2px solid rgba(255,255,255,0.25); border-radius: 8px;");
    local_video_->hide();
    local_video_->setAttribute(Qt::WA_TransparentForMouseEvents, true);

    // Create stats_label_ (bottom overlay) in remote_container_
    stats_label_ = new QLabel(remote_container_);
    stats_label_->setObjectName("statsLabel");
    stats_label_->setAlignment(Qt::AlignCenter);
    stats_label_->setStyleSheet(
        "color: white; background: rgba(0,0,0,120); padding: 2px;");

    // Install resize event filter for overlay positioning
    if (remote_container_) {
        remote_container_->installEventFilter(this);
    }

    // Additional configuration not expressible in .ui
    ui.peer_tree_->setHeaderLabels({"ID", "名称", "状态"});
    ui.peer_tree_->setMaximumHeight(220);
    ui.chat_display_->setObjectName("chatDisplay");
    ui.send_button_->setObjectName("sendButton");
    ui.log_area_->setObjectName("logArea");

    // Unified font sizes (Qt5 uic doesn't support <pointsize> in .ui)
    ui.stats_group_->setStyleSheet("QLabel { font-size: 12px; }");
    ui.chat_title_->setStyleSheet("font-size: 16px; font-weight: bold;");

    // ---- Toolbar ----
    toolbar_ = addToolBar("Main");
    toolbar_->setMovable(false);

    action_connect_ = toolbar_->addAction("连接");
    action_disconnect_ = toolbar_->addAction("断开");
    action_disconnect_->setEnabled(false);
    toolbar_->addSeparator();

    peer_input_ = new QLineEdit();
    peer_input_->setPlaceholderText("对端ID或名称");
    peer_input_->setMaximumWidth(180);
    peer_input_->setEnabled(false);
    toolbar_->insertWidget(toolbar_->actions().at(3), peer_input_);

    action_call_ = toolbar_->addAction("呼叫");
    action_call_->setEnabled(false);
    action_hangup_ = toolbar_->addAction("挂断");
    action_hangup_->setEnabled(false);
    toolbar_->addSeparator();

    action_ai_ = toolbar_->addAction("启动AI");
    action_ai_->setEnabled(false);
    action_ai_->setToolTip("切换YOLOv5目标检测");

    action_fall_ = toolbar_->addAction("跌倒检测");
    action_fall_->setEnabled(false);
    action_fall_->setToolTip("切换跌倒检测");

    action_fire_ = toolbar_->addAction("火灾检测");
    action_fire_->setEnabled(false);
    action_fire_->setToolTip("切换火灾/烟雾检测");
    toolbar_->addSeparator();

    action_voice_chat_ = toolbar_->addAction("语音对话");
    action_voice_chat_->setEnabled(false);
    action_voice_chat_->setToolTip("切换语音对话");

    statusBar()->showMessage("Starting...");
}

void MainWindow::initConnections() {
    // Process manager
    connect(proc_mgr_, &WebRtcProcessManager::stateChanged,
            this, &MainWindow::onProcessStateChanged);
    connect(proc_mgr_, &WebRtcProcessManager::daemonLog,
            this, &MainWindow::log);

    // Control channel
    connect(channel_, &ControlChannel::connected,
            this, &MainWindow::onControlConnected);
    connect(channel_, &ControlChannel::disconnected,
            this, &MainWindow::onControlDisconnected);
    connect(channel_, &ControlChannel::peerListReceived,
            this, &MainWindow::onPeerListReceived);

    connect(channel_, &ControlChannel::serverConnected, this, [this]() {
        log("Server connected");
        first_connect_ = false;
        action_connect_->setEnabled(false);
        action_disconnect_->setEnabled(true);
        statusBar()->showMessage("Connected to signaling server");
        QTimer::singleShot(200, this, [this]() {
            voice_chat_startup_complete_ = true;
            updateVoiceChatEnabled();
        });
    });
    connect(channel_, &ControlChannel::serverDisconnected, this, [this]() {
        log("Server disconnected");
        is_call_active_ = false;
        action_connect_->setEnabled(true);
        action_disconnect_->setEnabled(false);
        action_call_->setEnabled(false);
        action_hangup_->setEnabled(false);
        action_voice_chat_->setEnabled(false);
        stopVoiceChat();
        statusBar()->showMessage("Disconnected");
    });

    connect(channel_, &ControlChannel::callConnected, this, [this]() {
        log("Call connected, waiting for ICE...");
        is_call_active_ = true;
        action_call_->setEnabled(false);
        peer_input_->setEnabled(false);
        action_hangup_->setEnabled(true);
        action_ai_->setEnabled(true);
        action_fall_->setEnabled(true);
        action_fire_->setEnabled(true);
        action_voice_chat_->setEnabled(false);
        stopVoiceChat();
        statusBar()->showMessage("Call in progress — waiting for ICE...");
    });

    connect(channel_, &ControlChannel::callDisconnected, this, [this]() {
        log("Call disconnected, restarting daemon...");
        is_call_active_ = false;
        stopAi();
        action_hangup_->setEnabled(false);
        action_ai_->setEnabled(false);
        action_fall_->setEnabled(false);
        action_fire_->setEnabled(false);
        action_voice_chat_->setEnabled(false);
        stopVoiceChat();
        stopVideoSources();
        switchToListMode();
        ui.chat_input_->setEnabled(false);
        ui.send_button_->setEnabled(false);
        ui.chat_list_input_->setEnabled(false);
        ui.send_list_btn_->setEnabled(false);

        bool was_first = first_connect_;
        first_connect_ = true; // force auto-reconnect after restart
        channel_->cmdDisconnect();
        QTimer::singleShot(500, this, [this, was_first]() {
            proc_mgr_->stop();
            QTimer::singleShot(1000, this, [this, was_first]() {
                log("Starting new daemon instance...");
                QString rdir = qEnvironmentVariable("WEBRTC_RUNTIME_DIR",
                                                    "/tmp/webrtc_runtime");
                first_connect_ = was_first;
                proc_mgr_->start();
            });
        });
    });

    // DataChannel
    connect(channel_, &ControlChannel::dataChannelStateChanged, this,
            [this](const QString& state) {
        log("DataChannel: " + state);
        bool open = (state == "open");
        ui.chat_input_->setEnabled(open);
        ui.send_button_->setEnabled(open);
        if (open) ui.chat_display_->appendPlainText("--- DataChannel open ---");
    });
    connect(channel_, &ControlChannel::dataReceived, this,
            [this](const QString& text) {
        ui.chat_display_->appendPlainText("Peer: " + text);
        if (handleRemoteKey(text))
            return;  // motion command — handled, skip rest
        if (text == "AI:ON:yolov5") {
            stopAi();
            if (startAi(AiType::YoloV5)) {
                action_ai_->setText("停止AI");
                action_fall_->setText("跌倒检测");
                action_fire_->setText("火灾检测");
                channel_->cmdSendData("AI:ON_OK:yolov5");
            }
        }
        else if (text == "AI:ON:fall") {
            stopAi();
            if (startAi(AiType::Fall)) {
                action_ai_->setText("启动AI");
                action_fall_->setText("停止跌倒");
                action_fire_->setText("火灾检测");
                channel_->cmdSendData("AI:ON_OK:fall");
            }
        }
        else if (text == "AI:ON:fire") {
            stopAi();
            if (startAi(AiType::Fire)) {
                action_ai_->setText("启动AI");
                action_fall_->setText("跌倒检测");
                action_fire_->setText("停止火灾");
                channel_->cmdSendData("AI:ON_OK:fire");
            }
        }
        else if (text == "AI:OFF") {
            stopAi();
            resetAllAiButtons();
            channel_->cmdSendData("AI:OFF_OK");
        }
        else if (text == "AI:ON_OK:yolov5") {
            action_ai_->setText("停止AI");
            action_fall_->setText("跌倒检测");
            action_fire_->setText("火灾检测");
        }
        else if (text == "AI:ON_OK:fall") {
            action_ai_->setText("启动AI");
            action_fall_->setText("停止跌倒");
            action_fire_->setText("火灾检测");
        }
        else if (text == "AI:ON_OK:fire") {
            action_ai_->setText("启动AI");
            action_fall_->setText("跌倒检测");
            action_fire_->setText("停止火灾");
        }
        else if (text == "AI:OFF_OK") { resetAllAiButtons(); }
        else if (text.startsWith("AI:DET:")) {
            // Forward to AiReceiver parse (same format as reason output)
            QByteArray detJson = text.mid(7).toUtf8();
            // Parse and set detections directly
            QJsonParseError err;
            QJsonDocument doc = QJsonDocument::fromJson(detJson, &err);
            if (err.error == QJsonParseError::NoError) {
                QVector<Detection> dets;
                QJsonArray arr = doc.object()["dets"].toArray();
                for (const auto& v : arr) {
                    QJsonObject d = v.toObject();
                    Detection det;
                    det.cls_id = d["cls"].toInt();
                    det.label = d["label"].toString();
                    det.conf = (float)d["conf"].toDouble();
                    QJsonArray box = d["box"].toArray();
                    if (box.size() >= 4) {
                        det.left = box[0].toInt(); det.top = box[1].toInt();
                        det.right = box[2].toInt(); det.bottom = box[3].toInt();
                    }
                    dets.append(det);
                }
                local_video_->setDetections(dets);
            }
        }
    });

    // Errors
    connect(channel_, &ControlChannel::iceStateChanged, this, [this](const QString& s) {
        statusBar()->showMessage("ICE: " + s);
        if (s == "connected") {
            log("ICE connected, starting video...");
            switchToCallMode();
            startVideoSources();
        }
    });
    connect(channel_, &ControlChannel::errorOccurred, this, [this](const QString& e) {
        log("Channel error: " + e);
    });

    // Toolbar actions
    connect(action_connect_, &QAction::triggered, this, [this]() {
        channel_->cmdConnect(server_addr_, server_port_);
        log(QString("Connecting to %1:%2...").arg(server_addr_).arg(server_port_));
    });
    connect(action_disconnect_, &QAction::triggered, this, [this]() {
        channel_->cmdDisconnect();
    });
    connect(action_call_, &QAction::triggered, this, [this]() {
        if (peers_.isEmpty()) return;
        QString input = peer_input_->text().trimmed();
        if (input.isEmpty()) {
            doCall(peers_.first().id);
        } else {
            bool is_number;
            int id = input.toInt(&is_number);
            if (is_number) {
                doCall(id);
            } else {
                for (const auto& p : peers_) {
                    if (p.name.contains(input, Qt::CaseInsensitive)) {
                        doCall(p.id);
                        return;
                    }
                }
                log(QString("Peer not found: \"%1\"").arg(input));
            }
        }
    });
    connect(action_hangup_, &QAction::triggered, this, [this]() {
        channel_->cmdHangup();
    });
    connect(action_ai_, &QAction::triggered, this, [this]() {
        if (ai_type_ == AiType::YoloV5 && ai_proc_ && ai_proc_->state() == QProcess::Running) {
            stopAi();
            channel_->cmdSendData("AI:OFF_OK");
            resetAllAiButtons();
        } else {
            stopAi();
            if (startAi(AiType::YoloV5)) {
                channel_->cmdSendData("AI:ON_OK:yolov5");
                action_ai_->setText("停止AI");
                action_fall_->setText("跌倒检测");
                action_fire_->setText("火灾检测");
            }
        }
    });

    connect(action_fall_, &QAction::triggered, this, [this]() {
        if (ai_type_ == AiType::Fall && ai_proc_ && ai_proc_->state() == QProcess::Running) {
            stopAi();
            channel_->cmdSendData("AI:OFF_OK");
            resetAllAiButtons();
        } else {
            stopAi();
            if (startAi(AiType::Fall)) {
                channel_->cmdSendData("AI:ON_OK:fall");
                action_ai_->setText("启动AI");
                action_fall_->setText("停止跌倒");
                action_fire_->setText("火灾检测");
            }
        }
    });

    connect(action_fire_, &QAction::triggered, this, [this]() {
        if (ai_type_ == AiType::Fire && ai_proc_ && ai_proc_->state() == QProcess::Running) {
            stopAi();
            channel_->cmdSendData("AI:OFF_OK");
            resetAllAiButtons();
        } else {
            stopAi();
            if (startAi(AiType::Fire)) {
                channel_->cmdSendData("AI:ON_OK:fire");
                action_ai_->setText("启动AI");
                action_fall_->setText("跌倒检测");
                action_fire_->setText("停止火灾");
            }
        }
    });

    // Peer list double-click
    connect(ui.peer_tree_, &QTreeWidget::itemDoubleClicked,
            this, &MainWindow::onPeerDoubleClicked);

    // Peer input enter
    connect(peer_input_, &QLineEdit::returnPressed, action_call_, &QAction::trigger);

    // DataChannel send
    connect(ui.send_button_, &QPushButton::clicked, this, &MainWindow::doSendMessage);
    connect(ui.chat_input_, &QLineEdit::returnPressed, this, &MainWindow::doSendMessage);
    connect(ui.send_list_btn_, &QPushButton::clicked, this, [this]() {
        QString text = ui.chat_list_input_->text().trimmed();
        if (text.isEmpty()) return;
        channel_->cmdSendData(text);
        ui.chat_display_->appendPlainText("Me: " + text);
        ui.chat_list_input_->clear();
        ui.chat_list_input_->setFocus();
    });
    connect(ui.chat_list_input_, &QLineEdit::returnPressed, this, [this]() {
        ui.send_list_btn_->clicked();
    });

    // Stats timer
    stats_timer_ = new QTimer(this);
    stats_timer_->setInterval(1000);
    connect(stats_timer_, &QTimer::timeout, this, &MainWindow::onUpdateStats);

    // Stats monitoring button
    connect(ui.stats_monitor_btn_, &QPushButton::clicked, this, [this]() {
        if (!stats_monitoring_) {
            channel_->cmdStartStats();
            stats_monitoring_ = true;
            ui.stats_monitor_btn_->setText("测量关闭");
        } else {
            channel_->cmdStopStats();
            stats_monitoring_ = false;
            ui.stats_monitor_btn_->setText("测量启动");
        }
    });
    connect(channel_, SIGNAL(statsReceived(QJsonObject)), this, SLOT(onStatsReceived(QJsonObject)));
}

void MainWindow::onProcessStateChanged(WebRtcProcessManager::State state) {
    switch (state) {
    case WebRtcProcessManager::Running:
        log("Daemon started, connecting socket...");
        updateVoiceChatEnabled();
        QTimer::singleShot(500, this, [this]() {
            channel_->connectToServer();
        });
        break;
    case WebRtcProcessManager::Stopped:
        log("Daemon stopped");
        is_call_active_ = false;
        action_hangup_->setEnabled(false);
        break;
    case WebRtcProcessManager::Error:
        log("Daemon error - check binary path");
        is_call_active_ = false;
        action_hangup_->setEnabled(false);
        statusBar()->showMessage("Daemon failed to start");
        break;
    default:
        break;
    }
}

void MainWindow::onControlConnected() {
    log("Control channel connected");
    if (first_connect_) {
        log("Auto-connecting to signaling server...");
        channel_->cmdConnect(server_addr_, server_port_);
    }
}

void MainWindow::onControlDisconnected() {
    log("Control channel disconnected");
    is_call_active_ = false;
    action_hangup_->setEnabled(false);
}

void MainWindow::onPeerListReceived(QVector<PeerInfo> peers) {
    peers_ = peers;
    log("Peer list updated:");
    ui.peer_tree_->clear();
    for (const auto& p : peers) {
        auto* item = new QTreeWidgetItem(ui.peer_tree_);
        item->setText(0, QString::number(p.id));
        item->setText(1, p.name);
        item->setText(2, "Online");
        item->setData(0, Qt::UserRole, p.id);
    }
    bool has_peer = !peers.isEmpty();
    action_call_->setEnabled(has_peer);
    peer_input_->setEnabled(has_peer);
    action_hangup_->setEnabled(is_call_active_);
    updateVoiceChatEnabled();
    if (has_peer) {
        const auto& first = peers.first();
        peer_input_->setPlaceholderText(
            QString("ID %1 \"%2\"").arg(first.id).arg(first.name));
    } else {
        peer_input_->setPlaceholderText("No peers online");
    }
    statusBar()->showMessage(QString("%1 peer(s) online").arg(peers.size()));
}

void MainWindow::onPeerDoubleClicked(QTreeWidgetItem* item, int column) {
    Q_UNUSED(column);
    int peer_id = item->data(0, Qt::UserRole).toInt();
    doCall(peer_id);
}

bool MainWindow::eventFilter(QObject* obj, QEvent* event) {
    if (obj == remote_container_ && event->type() == QEvent::Resize) {
        int cw = remote_container_->width();
        int ch = remote_container_->height();

        // --- PIP (local_video_) ---
        constexpr double PIP_SCALE = 0.22;
        constexpr int PIP_MIN_W = 160;
        constexpr int PIP_MAX_W = 480;
        constexpr int PIP_MARGIN = 16;

        int pip_w = qBound(PIP_MIN_W, int(cw * PIP_SCALE), PIP_MAX_W);
        int pip_h = pip_w * 3 / 4;
        int pip_x = cw - pip_w - PIP_MARGIN;
        int pip_y = PIP_MARGIN;

        QRect currentGeo = local_video_->geometry();
        if (currentGeo.x() != pip_x || currentGeo.y() != pip_y ||
            currentGeo.width() != pip_w || currentGeo.height() != pip_h) {
            local_video_->setGeometry(pip_x, pip_y, pip_w, pip_h);
        }

        // --- stats_label_ ---
        constexpr int STATS_W = 420;
        constexpr int STATS_H = 28;
        constexpr int STATS_BOTTOM_MARGIN = 8;
        int stats_x = (cw - STATS_W) / 2;
        int stats_y = ch - STATS_H - STATS_BOTTOM_MARGIN;
        stats_label_->setGeometry(stats_x, stats_y, STATS_W, STATS_H);

        local_video_->raise();
        stats_label_->raise();
    }
    return QMainWindow::eventFilter(obj, event);
}

void MainWindow::doCall(int peer_id) {
    stopVoiceChat();
    channel_->cmdCall(peer_id);
    log(QString("Calling peer %1...").arg(peer_id));
}

void MainWindow::switchToListMode() {
    ui.stack_->setCurrentIndex(0);
    centralWidget()->layout()->setContentsMargins(0, 0, 0, 0);
    ui.log_area_->setVisible(true);
    if (local_video_)
        local_video_->hide();
    stats_timer_->stop();
}

void MainWindow::switchToCallMode() {
    ui.stack_->setCurrentIndex(1);
    centralWidget()->layout()->setContentsMargins(0, 0, 0, 0);
    ui.log_area_->setVisible(false);
    stats_label_->show();
    stats_label_->raise();
    stats_timer_->start();
    // Force initial 80:20 splitter ratio after layout recalculation.
    QTimer::singleShot(0, this, [this]() {
        auto* sp = centralWidget()->findChild<QSplitter*>("callSplitter");
        if (!sp) return;
        int totalW = sp->width();
        if (totalW > 0) {
            sp->setSizes({totalW * 80 / 100, totalW * 20 / 100});
        }
    });
}

void MainWindow::startVideoSources() {
    QString rdir = qEnvironmentVariable("WEBRTC_RUNTIME_DIR",
                                        "/tmp/webrtc_runtime");

    local_source_ = new DmaBufVideoSource(
        rdir + "/shm_video_buf_local", 0x89,
        rdir + "/shm_video_buf_local_socket", this);
    remote_source_ = new DmaBufVideoSource(
        rdir + "/shm_video_buf_remote", 0x8a,
        rdir + "/shm_video_buf_remote_socket", this);

    connect(local_source_, &DmaBufVideoSource::frameReady, this,
            [this](const QImage& f, int w, int h) {
        local_width_ = w;
        local_height_ = h;
        local_frame_count_++;
        if (local_video_) {
            local_video_->setFrame(f);
            if (!local_video_->isVisible()) {
                local_video_->show();
                // Position at top-right; delay slightly to ensure layout is done
                QTimer::singleShot(100, this, [this]() {
                    int x = (remote_container_ ? remote_container_->width() : 640) - local_video_->width() - 20;
                    int y = 10;
                    local_video_->move(qMax(0, x), y);
                    local_video_->raise();
                });
            }
            local_video_->raise();
        }
    });
    bool* call_mode_entered = new bool(false);
    connect(remote_source_, &DmaBufVideoSource::frameReady, this,
            [this, call_mode_entered](const QImage& f, int w, int h) {
        remote_width_ = w;
        remote_height_ = h;
        remote_frame_count_++;
        ui.remote_video_->setFrame(f);
        if (!*call_mode_entered) {
            *call_mode_entered = true;
            switchToCallMode();
        }
    });

    connect(local_source_, &DmaBufVideoSource::errorOccurred, this,
            [this](const QString& e) { log("Local video error: " + e); });
    connect(remote_source_, &DmaBufVideoSource::errorOccurred, this,
            [this](const QString& e) { log("Remote video error: " + e); });

    local_source_->start();
    remote_source_->start();
    log("Video sources started (DMA-BUF + RGA)");
}

void MainWindow::stopVideoSources() {
    if (local_source_) {
        local_source_->stop();
        local_source_->deleteLater();
        local_source_ = nullptr;
    }
    if (remote_source_) {
        remote_source_->stop();
        remote_source_->deleteLater();
        remote_source_ = nullptr;
    }
}

void MainWindow::doSendMessage() {
    QString text = ui.chat_input_->text().trimmed();
    if (text.isEmpty()) return;
    channel_->cmdSendData(text);
    ui.chat_display_->appendPlainText("Me: " + text);
    ui.chat_input_->clear();
    ui.chat_input_->setFocus();
}

void MainWindow::onUpdateStats() {
    QString stats = QString("Remote: %1x%2 %3fps | Local: %4x%5 %6fps")
                        .arg(remote_width_).arg(remote_height_)
                        .arg(remote_frame_count_)
                        .arg(local_width_).arg(local_height_)
                        .arg(local_frame_count_);
    stats_label_->setText(stats);
    remote_frame_count_ = 0;
    local_frame_count_ = 0;
}
void MainWindow::onStatsReceived(const QJsonObject& s) {
    

    auto color = [](double v, double green, double yellow) -> QString {
        if (v <= green) return "color:#27ae60;";
        if (v <= yellow) return "color:#f39c12;";
        return "color:#e74c3c;";
    };
    auto setColored = [](QLabel* lb, const QString& text, double val, double green, double yellow) {
        QString c = (val <= green) ? "color:#27ae60;" : (val <= yellow) ? "color:#f39c12;" : "color:#e74c3c;";
        lb->setText(text);
        lb->setStyleSheet("font-size:11px; padding:1px 2px; " + c);
    };

    // Connection state
    QString iceType = s.value("local_cand_type").toString();
    bool writable = s.value("ice_writable").toBool();
    if (writable) {
        ui.stats_conn_->setText(QString("连接: 正常 (%1)").arg(iceType));
        ui.stats_conn_->setStyleSheet("font-size:11px; padding:1px 2px; color:#27ae60;");
    } else {
        ui.stats_conn_->setText("连接: 检查中");
        ui.stats_conn_->setStyleSheet("font-size:11px; padding:1px 2px; color:#f39c12;");
    }

    // RTT (ms)
    if (s.contains("rtt_s")) {
        double rtt = s["rtt_s"].toDouble() * 1000.0;
        setColored(ui.stats_rtt_, QString("延迟: %1ms").arg(rtt, 0, 'f', 1), rtt, 50, 200);
    }
    // Loss rate
    if (s.contains("loss_rate_pct")) {
        double loss = s["loss_rate_pct"].toDouble();
        setColored(ui.stats_loss_, QString("丢包: %1%").arg(loss, 0, 'f', 1), loss, 1, 3);
    }
    // Send quality
    if (s.contains("encode_fps") && s.contains("encode_h")) {
        int fps = s["encode_fps"].toInt();
        int w = s["encode_w"].toInt();
        int h = s["encode_h"].toInt();
        QString txt = QString("发送: %1×%2 %3fps").arg(w).arg(h).arg(fps);
        ui.stats_send_quality_->setText(txt);
        QString c = (fps >= 25) ? "color:#27ae60;" : (fps >= 15) ? "color:#f39c12;" : "color:#e74c3c;";
        ui.stats_send_quality_->setStyleSheet("font-size:11px; padding:1px 2px; " + c);
    }
    // Recv quality
    if (s.contains("decode_fps") && s.contains("decode_h")) {
        int fps = s["decode_fps"].toInt();
        int w = s["decode_w"].toInt();
        int h = s["decode_h"].toInt();
        QString txt = QString("接收: %1×%2 %3fps").arg(w).arg(h).arg(fps);
        ui.stats_recv_quality_->setText(txt);
        QString c = (fps >= 25) ? "color:#27ae60;" : (fps >= 15) ? "color:#f39c12;" : "color:#e74c3c;";
        ui.stats_recv_quality_->setStyleSheet("font-size:11px; padding:1px 2px; " + c);
    }
    // Send rate
    if (s.contains("send_kbps")) {
        int kbps = s["send_kbps"].toInt();
        int target = s.value("target_kbps").toInt(0);
        double ratio = target > 0 ? (double)kbps / target : 1.0;
        QString txt = QString("发送码率: %1kbps").arg(kbps);
        ui.stats_send_rate_->setText(txt);
        QString c = (ratio >= 0.8) ? "color:#27ae60;" : (ratio >= 0.5) ? "color:#f39c12;" : "color:#e74c3c;";
        ui.stats_send_rate_->setStyleSheet("font-size:11px; padding:1px 2px; " + c);
    }
    // Recv rate
    if (s.contains("recv_kbps")) {
        int kbps = s["recv_kbps"].toInt();
        ui.stats_recv_rate_->setText(QString("接收码率: %1kbps").arg(kbps));
        ui.stats_recv_rate_->setStyleSheet("color:#27ae60;");
    }
    // Quality limitation reason (the most important diagnostic)
    if (s.contains("quality_limit")) {
        QString ql = s["quality_limit"].toString();
        QString txt = QString("降质: %1").arg(ql);
        ui.stats_limit_->setText(txt);
        QString c = (ql == "none") ? "color:#27ae60;" : (ql == "cpu") ? "color:#f39c12;" : "color:#e74c3c;";
        ui.stats_limit_->setStyleSheet(c);
    }
    // Encode time
    if (s.contains("avg_encode_ms")) {
        int ms = s["avg_encode_ms"].toInt();
        setColored(ui.stats_encode_ms_, QString("编码: %1ms").arg(ms), ms, 20, 33);
    }
    // Decode time
    if (s.contains("avg_decode_ms")) {
        int ms = s["avg_decode_ms"].toInt();
        setColored(ui.stats_decode_ms_, QString("解码: %1ms").arg(ms), ms, 10, 20);
    }
    // Available bandwidth
    if (s.contains("avail_kbps")) {
        int avail = s["avail_kbps"].toInt();
        int target = s.value("target_kbps").toInt(0);
        QString txt = QString("可用带宽: %1kbps").arg(avail);
        ui.stats_avail_kbps_->setText(txt);
        double ratio = target > 0 ? (double)avail / target : 2.0;
        QString c = (ratio >= 1.5) ? "color:#27ae60;" : (ratio >= 1.0) ? "color:#f39c12;" : "color:#e74c3c;";
        ui.stats_avail_kbps_->setStyleSheet(c);
    }
    // Freeze count (visible quality drops)
    if (s.contains("freeze_cnt")) {
        int fz = s["freeze_cnt"].toInt();
        ui.stats_freeze_->setText(QString("冻结: %1").arg(fz));
        QString c = (fz == 0) ? "color:#27ae60;" : (fz <= 3) ? "color:#f39c12;" : "color:#e74c3c;";
        ui.stats_freeze_->setStyleSheet(c);
    }
}

void MainWindow::log(const QString& msg) {
    ui.log_area_->appendPlainText(msg);
    if (log_file_ && log_file_->isOpen()) {
        QTextStream ts(log_file_);
        ts << QDateTime::currentDateTime().toString("HH:mm:ss.zzz") << " " << msg << "\n";
        ts.flush();
    }
}

void MainWindow::chatLog(const QString& msg) {
    ui.chat_list_->appendPlainText(msg);
}

void MainWindow::keyPressEvent(QKeyEvent* event) {
    if (event->isAutoRepeat()) return;
    int k = event->key();
    if (k == Qt::Key_W || k == Qt::Key_A || k == Qt::Key_S || k == Qt::Key_D ||
        k == Qt::Key_Up || k == Qt::Key_Left || k == Qt::Key_Down || k == Qt::Key_Right) {
        held_key_ = k;
        startKeyRepeat();
    }
    QMainWindow::keyPressEvent(event);
}

void MainWindow::keyReleaseEvent(QKeyEvent* event) {
    if (event->isAutoRepeat()) return;
    if (event->key() == held_key_) stopKeyRepeat();
    QMainWindow::keyReleaseEvent(event);
}

void MainWindow::startKeyRepeat() { key_timer_->start(); }
void MainWindow::stopKeyRepeat() { held_key_ = 0; key_timer_->stop(); }

bool MainWindow::handleRemoteKey(const QString& text) {
    QJsonParseError err;
    QJsonDocument doc = QJsonDocument::fromJson(text.toUtf8(), &err);
    if (err.error != QJsonParseError::NoError || !doc.isObject())
        return false;  // not JSON — treat as chat/AI message

    QJsonObject obj = doc.object();
    QString cmd = obj["cmd"].toString();
    if (cmd == "move" || cmd == "ptz" || cmd == "move_ptz" ||
        cmd == "ptz_home" || cmd == "stop") {
        sendSerialJson(text);  // forward to MCU as-is
        return true;
    }
    return false;  // JSON but not a motion command — treat as chat/AI
}

void MainWindow::sendSerialJson(const QString& json) {
    if (serial_) serial_->enqueue(json);
}

static const char* ai_type_label(AiType t) {
    switch (t) {
    case AiType::YoloV5: return "YOLOv5";
    case AiType::Fall:   return "跌倒检测";
    case AiType::Fire:   return "火灾检测";
    default:             return "None";
    }
}

void MainWindow::resetAllAiButtons() {
    action_ai_->setText("启动AI");
    action_fall_->setText("跌倒检测");
    action_fire_->setText("火灾检测");
}

bool MainWindow::startAi(AiType type) {
    if (ai_proc_ && ai_proc_->state() == QProcess::Running) {
        log("AI already running, stopping first");
        stopAi();
    }

    QString models_dir = QCoreApplication::applicationDirPath() + "/models";
    QString binary, model, labels;
    QStringList extra_args;

    switch (type) {
    case AiType::YoloV5:
        binary = models_dir + "/yolov5-coco80/reason";
        model  = models_dir + "/yolov5-coco80/yolov5.rknn";
        labels = models_dir + "/yolov5-coco80/coco_80_labels_list.txt";
        extra_args << "--filter-cls=0,64";
        break;
    case AiType::Fall:
        binary = models_dir + "/yolov11-human-fall-detection/fall_detect";
        model  = models_dir + "/yolov11-human-fall-detection/best.rknn";
        labels = models_dir + "/yolov11-human-fall-detection/labels_fall.txt";
        break;
    case AiType::Fire:
        binary = models_dir + "/yolov8-fire-smoke-detection/fire_detect";
        model  = models_dir + "/yolov8-fire-smoke-detection/best.rknn";
        labels = models_dir + "/yolov8-fire-smoke-detection/labels_fire.txt";
        break;
    default:
        log("Unknown AI type");
        return false;
    }

    if (!ai_proc_) {
        ai_proc_ = new QProcess(this);
        connect(ai_proc_, &QProcess::started, this, [this]() {
            log(QString("AI process started (pid=%1 type=%2)")
                .arg(ai_proc_->processId()).arg(ai_type_label(ai_type_)));
        });
        connect(ai_proc_, QOverload<int,QProcess::ExitStatus>::of(&QProcess::finished),
                this, [this](int code, QProcess::ExitStatus st) {
            log(QString("AI process exited code=%1 status=%2")
                .arg(code).arg(st == QProcess::NormalExit ? "normal" : "crash"));
            resetAllAiButtons();
            local_video_->setDetections({});
            ai_type_ = AiType::None;
        });
        connect(ai_proc_, &QProcess::errorOccurred, this, [this](QProcess::ProcessError e) {
            log(QString("AI process error: %1").arg(e));
        });
    }

    ai_type_ = type;
    log(QString("Starting AI (%1): %2").arg(ai_type_label(type)).arg(binary));

    QStringList args;
    args << "--ctrl-shm=/tmp/webrtc_runtime/shm_video_buf_local"
         << "--proj-id=0x89"
         << "--dma-socket=/tmp/webrtc_runtime/shm_video_buf_local_socket"
         << "--model=" + model
         << "--infer-interval-ms=250"
         << "--result-socket=/tmp/webrtc_runtime/ai_detections.sock"
         << "--labels=" + labels
         << "--conf-threshold=0.45"
         << extra_args;
    ai_proc_->start(binary, args);
    return true;
}

void MainWindow::stopAi() {
    if (ai_proc_ && ai_proc_->state() == QProcess::Running) {
        log(QString("Stopping AI process (%1)...").arg(ai_type_label(ai_type_)));
        ai_proc_->terminate();
        if (!ai_proc_->waitForFinished(3000)) {
            log("AI process did not stop, killing...");
            ai_proc_->kill();
            ai_proc_->waitForFinished(2000);
        }
        log("AI stopped, boxes cleared");
    }
    ai_type_ = AiType::None;
    local_video_->setDetections({});
    resetAllAiButtons();
}

void MainWindow::onAiDetections(QVector<Detection> detections) {
    local_video_->setDetections(detections);
    // Forward to x64 via DataChannel
    QJsonObject root;
    root["ts"] = (qint64)0;
    QJsonArray arr;
    for (const auto& d : detections) {
        QJsonObject o;
        o["cls"] = d.cls_id;
        o["label"] = d.label;
        o["conf"] = d.conf;
        QJsonArray box;
        box.append(d.left); box.append(d.top); box.append(d.right); box.append(d.bottom);
        o["box"] = box;
        arr.append(o);
    }
    root["dets"] = arr;
    QJsonDocument doc(root);
    channel_->cmdSendData("AI:DET:" + QString::fromUtf8(doc.toJson(QJsonDocument::Compact)));
}

void MainWindow::toggleVoiceChat()
{
    if (!voice_chat_startup_complete_) return;
    if (voice_chat_running_) {
        stopVoiceChat();
    } else {
        QString runtime_dir = qEnvironmentVariable("WEBRTC_RUNTIME_DIR",
                                                    "/tmp/webrtc_runtime");
        QString vc_socket = runtime_dir + "/voice_chat.sock";
        voice_mgr_->start(vc_socket);
        voice_chat_running_ = true;
        action_voice_chat_->setText("停止语音");
        ui.chat_list_input_->setEnabled(true);
        ui.send_list_btn_->setEnabled(true);
        QTimer::singleShot(500, this, [this]() {
            voice_client_->connectToServer();
        });
        log("Voice chat started");
    }
}

void MainWindow::stopVoiceChat()
{
    if (!voice_chat_running_) return;
    voice_client_->cmdStop();
    voice_client_->disconnectFromServer();
    voice_mgr_->stop();
    voice_chat_running_ = false;
    action_voice_chat_->setText("语音对话");
    action_voice_chat_->setEnabled(false);
    ui.chat_list_input_->setEnabled(false);
    ui.send_list_btn_->setEnabled(false);
    updateVoiceChatEnabled();
    log("Voice chat stopped");
}

void MainWindow::updateVoiceChatEnabled()
{
    bool ok = proc_mgr_->state() == WebRtcProcessManager::Running
           && !is_call_active_;
    action_voice_chat_->setEnabled(ok);
}
