import("//testing/test.gni")

rtc_test("unix_socket_server_test") {
  testonly = true

  sources = [
    "unix_socket_server_test.cc",
    "../../client/unix_socket_server.cc",
    "../../client/unix_socket_server.h",
  ]

  deps = [
    "//rtc_base:logging",
    "//third_party/jsoncpp",
  ]

  cflags = [ "-Wno-deprecated-declarations" ]
  libs = [ "pthread" ]
}
