import("../../../../webrtc.gni")

rtc_executable("video_capture_shm_mpp") {
  testonly = true

  sources = [
    "main.cc",
    "mpp_encoder_sink.cc",
    "mpp_encoder_sink.h",
    "../../client/rk_mpp_codec.cc",
    "../../client/rk_mpp_codec.h",
    "../../client/rk_mpp_stubs.cc",
    "../../client/shm_video_renderer.cc",
    "../../client/shm_video_renderer.h",
    "../../client/shm_video_writer.cc",
    "../../client/shm_video_writer.h",
    "../../client/shm_common.cc",
    "../../client/shm_common.h",
  ]

  deps = [
    "../../../../api/environment",
    "../../../../api/environment:environment_factory",
    "../../../../api/video:video_frame",
    "../../../../api/video_codecs:video_codecs_api",
    "../../../../api:create_frame_generator",
    "../../../../common_video:common_video",
    "../../../../modules/video_capture:video_capture_internal_impl",
    "../../../../modules/video_capture:video_capture_module",
    "../../../../modules/video_coding:video_codec_interface",
    "../../../../modules/video_coding:webrtc_h264",
    "../../../../rtc_base:logging",
    "../../../../system_wrappers:system_wrappers",
    "../../../../test:frame_generator_capturer",
    "../../../../test:platform_video_capturer",
    "../../../../test:test_video_capturer",
    "//third_party/abseil-cpp/absl/flags:flag",
    "//third_party/abseil-cpp/absl/flags:parse",
  ]

  cflags = [
    "-Wno-deprecated-declarations",
    "-Wno-unsafe-buffer-usage",
  ]
  include_dirs = [
    "../../mpp/inc",
    "../../mpp/osal/inc",
    "../../mpp/utils",
    "../../mpp/mpp/base/inc",
  ]
  libs = [
    "dl",
    "pthread",
  ]
}
