import("../../../../../webrtc.gni")

rtc_executable("openh264_enc") {
  testonly = true
  sources = [
    "main.cc",
    "../../../client/shm_common.cc", "../../../client/shm_common.h",
    "../../../client/shm_video_writer.cc", "../../../client/shm_video_writer.h",
  ]
  deps = [
    "../../../../../api/environment", "../../../../../api/environment:environment_factory",
    "../../../../../api/video:video_frame",
    "../../../../../api/video_codecs:video_codecs_api",
    "../../../../../api/video_codecs:video_encoder_factory_template_open_h264_adapter",
    "../../../../../api/video_codecs:video_encoder_factory_template",
    "../../../../../modules/video_capture:video_capture_internal_impl",
    "../../../../../modules/video_capture:video_capture_module",
    "../../../../../modules/video_coding:video_codec_interface",
    "../../../../../modules/video_coding:webrtc_h264",
    "../../../../../pc:video_track_source",
    "../../../../../rtc_base:logging",
    "../../../../../system_wrappers",
    "../../../../../test:frame_generator_capturer",
    "../../../../../test:platform_video_capturer",
    "../../../../../test:test_video_capturer",
    "//third_party/abseil-cpp/absl/flags:flag",
    "//third_party/abseil-cpp/absl/flags:parse",
  ]
  cflags = [ "-Wno-deprecated-declarations" ]
  libs = [ "pthread" ]
}
