import("../../../webrtc.gni")

if (is_linux || is_chromeos) {
  import("//build/config/linux/pkg_config.gni")
}

assert(is_linux || is_chromeos,
       "apps/peerconnection/client currently supports Linux/ChromeOS only.")

pkg_config("gtk_config") {
  packages = [
    # Gtk requires gmodule, but it does not list it as a dependency in some
    # misconfigured systems.
    "gmodule-2.0",
    "gthread-2.0",
    "gtk+-3.0",
  ]
}

rtc_executable("peerconnection_client") {
  testonly = true
  output_name = "apps_peerconnection_client"

  sources = [
    "conductor.cc",
    "conductor.h",
    "defaults.cc",
    "defaults.h",
    "flag_defs.h",
    "linux/main.cc",
    "linux/main_wnd.cc",
    "linux/main_wnd.h",
    "main_wnd.h",
    "peer_connection_client.cc",
    "peer_connection_client.h",
  ]

  deps = [
    "../../../api:async_dns_resolver",
    "../../../api:audio_options_api",
    "../../../api:create_frame_generator",
    "../../../api:create_modular_peer_connection_factory",
    "../../../api:data_channel_interface",
    "../../../api:enable_media",
    "../../../api:field_trials",
    "../../../api:jsep",
    "../../../api:make_ref_counted",
    "../../../api:media_stream_interface",
    "../../../api:peer_connection_interface",
    "../../../api:rtc_error",
    "../../../api:rtp_receiver_interface",
    "../../../api:rtp_sender_interface",
    "../../../api:scoped_refptr",
    "../../../api/audio:audio_device",
    "../../../api/audio:audio_mixer_api",
    "../../../api/audio:audio_processing",
    "../../../api/audio:create_audio_device_module",
    "../../../api/audio_codecs:audio_codecs_api",
    "../../../api/audio_codecs:builtin_audio_decoder_factory",
    "../../../api/audio_codecs:builtin_audio_encoder_factory",
    "../../../api/environment",
    "../../../api/environment:environment_factory",
    "../../../api/task_queue",
    "../../../api/task_queue:pending_task_safety_flag",
    "../../../api/units:time_delta",
    "../../../api/video:video_frame",
    "../../../api/video:video_rtp_headers",
    "../../../api/video_codecs:video_codecs_api",
    "../../../api/video_codecs:video_decoder_factory_template",
    "../../../api/video_codecs:video_decoder_factory_template_dav1d_adapter",
    "../../../api/video_codecs:video_decoder_factory_template_libvpx_vp8_adapter",
    "../../../api/video_codecs:video_decoder_factory_template_libvpx_vp9_adapter",
    "../../../api/video_codecs:video_decoder_factory_template_open_h264_adapter",
    "../../../api/video_codecs:video_encoder_factory_template",
    "../../../api/video_codecs:video_encoder_factory_template_libaom_av1_adapter",
    "../../../api/video_codecs:video_encoder_factory_template_libvpx_vp8_adapter",
    "../../../api/video_codecs:video_encoder_factory_template_libvpx_vp9_adapter",
    "../../../api/video_codecs:video_encoder_factory_template_open_h264_adapter",
    "../../../media:media_channel",
    "../../../media:video_common",
    "../../../modules/audio_device",
    "../../../modules/video_capture:video_capture_module",
    "../../../p2p:connection",
    "../../../p2p:port_allocator",
    "../../../pc:libjingle_peerconnection",
    "../../../pc:video_track_source",
    "../../../rtc_base:async_dns_resolver",
    "../../../rtc_base:buffer",
    "../../../rtc_base:checks",
    "../../../rtc_base:logging",
    "../../../rtc_base:net_helpers",
    "../../../rtc_base:refcount",
    "../../../rtc_base:rtc_certificate_generator",
    "../../../rtc_base:rtc_json",
    "../../../rtc_base:socket",
    "../../../rtc_base:socket_address",
    "../../../rtc_base:ssl_adapter",
    "../../../rtc_base:stringutils",
    "../../../rtc_base:threading",
    "../../../system_wrappers",
    "../../../test:frame_generator_capturer",
    "../../../test:platform_video_capturer",
    "../../../test:rtp_test_utils",
    "../../../test:test_video_capturer",
    "../../../test:video_test_common",
    "../../../media:rtc_audio_video",
    "../../../modules/audio_processing",
    "//third_party/abseil-cpp/absl/base:nullability",
    "//third_party/abseil-cpp/absl/flags:flag",
    "//third_party/abseil-cpp/absl/flags:parse",
    "//third_party/abseil-cpp/absl/memory",
    "//third_party/jsoncpp",
    "//third_party/libyuv",
  ]

  configs += [ ":gtk_config" ]
  cflags = [ "-Wno-deprecated-declarations" ]
  libs = [
    "X11",
    "Xcomposite",
    "Xext",
    "Xrender",
  ]
}
